# Generated by Django 2.1.7 on 2019-03-15 16:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Тип об`єкту')),
            ],
            options={
                'db_table': 'db_category',
            },
        ),
        migrations.CreateModel(
            name='dogovor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='№ договору')),
                ('dogovor_file', models.FileField(upload_to='dogovor', verbose_name='Скан договору')),
                ('date_start', models.DateField(default=datetime.date.today, verbose_name='Дата поч.')),
                ('date_finish', models.DateField(blank=True, null=True, verbose_name='Дата зак.')),
                ('state', models.CharField(choices=[('new', 'Новий'), ('per', 'Перезаключений'), ('pro', 'Пролонгований'), ('fin', 'Розірваний')], default='new', max_length=3, verbose_name='Тип')),
            ],
            options={
                'db_table': 'db_dogovor',
            },
        ),
        migrations.CreateModel(
            name='firms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=50, unique=True, verbose_name='Назва')),
                ('director', models.CharField(default='', max_length=100, verbose_name='Начальник')),
                ('yur_address', models.CharField(default='', max_length=255, verbose_name='Юр. адреса')),
                ('fiz_address', models.CharField(max_length=255, verbose_name='Фіз. адреса')),
                ('telephone1', models.CharField(default='', max_length=30, verbose_name='№ телефону')),
                ('telephone2', models.CharField(blank=True, max_length=30, verbose_name='№ телефону (дод)')),
            ],
            options={
                'db_table': 'db_firm',
            },
        ),
        migrations.CreateModel(
            name='regions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Назва району')),
                ('director', models.CharField(default='', max_length=100, verbose_name='Начальник району')),
                ('telephone', models.CharField(default='', max_length=30, verbose_name='№ телефону ч/ч')),
            ],
            options={
                'db_table': 'db_regions',
            },
        ),
        migrations.CreateModel(
            name='security_object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=255, unique=True, verbose_name='Назва')),
                ('address', models.CharField(default='', max_length=255, verbose_name='Адреса')),
                ('document', models.FileField(upload_to='object', verbose_name='Картка об`єкту')),
                ('state', models.CharField(choices=[('kv', 'Квартира (ОМГ)'), ('in', 'Інше')], default='', max_length=2, verbose_name='Тип')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.category', verbose_name='Категорія')),
                ('dogovor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.dogovor', verbose_name='Договір')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.firms', verbose_name='Ох. фірма')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.regions', verbose_name='Район')),
            ],
            options={
                'db_table': 'db_security_object',
            },
        ),
        migrations.AddField(
            model_name='dogovor',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.firms', verbose_name='Ох. фірма'),
        ),
    ]
